# Generated by Django 6.0.4 on 2026-04-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, default='🏥', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'specialties',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('bio_ar', models.TextField(blank=True)),
                ('consultation_fee_aed', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('consultation_fee_sar', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('consultation_fee_eur', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('available_from', models.TimeField(default='08:00')),
                ('available_to', models.TimeField(default='17:00')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_tele_health_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialty')),
            ],
        ),
    ]
