# Generated by Django 5.1.1 on 2026-04-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='telehealth_discount_percent',
            field=models.PositiveIntegerField(default=20, help_text='Discount percentage applied to TeleHealth consultations (e.g. 20 = 20% off in-person fee)'),
        ),
    ]
