# Generated by Django 5.1.1 on 2026-04-29 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_telehealth_discount_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name_plural': 'specialties'},
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='department',
            field=models.CharField(choices=[('GENERAL', 'General Medicine'), ('OPD', 'OPD'), ('CARDIOLOGY', 'Cardiology'), ('ORTHOPEDICS', 'Orthopedics'), ('NEUROLOGY', 'Neurology'), ('PEDIATRICS', 'Pediatrics'), ('DERMATOLOGY', 'Dermatology'), ('RADIOLOGY', 'Radiology'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.TextField(blank=True, help_text='Degrees and institutions'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, default='English', max_length=200),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_days',
            field=models.CharField(default='MON,TUE,WED,THU,FRI', help_text='Comma-separated: MON,TUE,WED,THU,FRI,SAT,SUN', max_length=40),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialty'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='telehealth_discount_percent',
            field=models.PositiveIntegerField(default=20, help_text='Discount % applied to TeleHealth fee vs in-person fee'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_active'], name='doctors_doc_is_acti_205e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['department'], name='doctors_doc_departm_f1ea26_idx'),
        ),
    ]
