# Generated by Django 5.1.1 on 2026-04-29 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='drug',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage_form',
            field=models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('PATCH', 'Patch'), ('SACHET', 'Sachet'), ('OTHER', 'Other')], default='TABLET', max_length=20),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drug',
            name='reorder_level',
            field=models.PositiveIntegerField(default=20, help_text='Trigger reorder when stock hits this level'),
        ),
        migrations.AddField(
            model_name='drug',
            name='reorder_quantity',
            field=models.PositiveIntegerField(default=100, help_text='Standard reorder quantity'),
        ),
        migrations.AddField(
            model_name='drug',
            name='requires_prescription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='storage_conditions',
            field=models.CharField(choices=[('ROOM_TEMP', 'Room Temperature'), ('REFRIGERATED', 'Refrigerated'), ('FROZEN', 'Frozen'), ('COOL_DRY', 'Cool & Dry')], default='ROOM_TEMP', max_length=20),
        ),
        migrations.AddField(
            model_name='drug',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g. 500mg, 10ml', max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='drug',
            name='unit_cost_aed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Purchase cost (for margin calculation)', max_digits=8),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_after',
            field=models.PositiveIntegerField(default=0, help_text='Stock level after this movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='stock_before',
            field=models.PositiveIntegerField(default=0, help_text='Stock level before this movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='drug',
            name='category',
            field=models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic / Pain Relief'), ('ANTIDIABETIC', 'Antidiabetic'), ('ANTIHYPERTENSIVE', 'Antihypertensive'), ('ANTIHISTAMINE', 'Antihistamine'), ('ANTIVIRAL', 'Antiviral'), ('VITAMIN', 'Vitamin / Supplement'), ('CARDIOVASCULAR', 'Cardiovascular'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('RESPIRATORY', 'Respiratory'), ('DERMATOLOGICAL', 'Dermatological'), ('OPHTHALMIC', 'Ophthalmic'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='drug',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='is_controlled',
            field=models.BooleanField(default=False, help_text='Controlled/narcotic substance'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='drug',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Dispensed)'), ('ADJUSTMENT', 'Manual Adjustment'), ('EXPIRED', 'Removed — Expired'), ('RETURN', 'Patient Return'), ('TRANSFER', 'Inter-dept Transfer')], max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Positive = added, Negative not used (use movement_type)'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reference',
            field=models.CharField(blank=True, help_text='Invoice/PO/Prescription ref', max_length=100),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['category'], name='pharmacy_dr_categor_ccdd05_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='pharmacy_dr_is_acti_aec0e7_idx'),
        ),
        migrations.AddIndex(
            model_name='drug',
            index=models.Index(fields=['expiry_date'], name='pharmacy_dr_expiry__636189_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['drug', 'created_at'], name='pharmacy_st_drug_id_57faa4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='pharmacy_st_movemen_ec6bc6_idx'),
        ),
    ]
