# Generated by Django 5.1.1 on 2026-04-29 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_specialty_options_doctorprofile_department_and_more'),
        ('queue_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queuetoken',
            options={'ordering': ['queue_date', 'is_priority', 'token_number']},
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='department',
            field=models.CharField(choices=[('GENERAL', 'General / Reception'), ('OPD', 'OPD'), ('PHARMACY', 'Pharmacy'), ('XRAY', 'X-Ray / Radiology'), ('LAB', 'Laboratory'), ('BILLING', 'Billing / Cashier'), ('EMERGENCY', 'Emergency')], db_index=True, default='GENERAL', max_length=16),
        ),
        migrations.AddField(
            model_name='queuetoken',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='patient_name',
            field=models.CharField(blank=True, help_text='For walk-in patients without account', max_length=150),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='queue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='queuetoken',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='WAITING', max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='queuetoken',
            unique_together={('queue_date', 'token_number', 'department')},
        ),
        migrations.AddIndex(
            model_name='queuetoken',
            index=models.Index(fields=['queue_date', 'department', 'status'], name='queue_mgmt__queue_d_83f699_idx'),
        ),
    ]
