# Generated by Django 5.1.1 on 2026-04-29 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_doctorprofile_telehealth_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(blank=True, max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('bp', models.CharField(blank=True, max_length=20, verbose_name='Blood Pressure')),
                ('temperature', models.CharField(blank=True, max_length=10)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('SEEN', 'Seen'), ('REFERRED', 'Referred'), ('DISCHARGED', 'Discharged')], default='WAITING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_referrals', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XRayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_phone', models.CharField(blank=True, max_length=30)),
                ('xray_type', models.CharField(choices=[('CHEST', 'Chest X-Ray'), ('KNEE', 'Knee'), ('SPINE', 'Spine'), ('PELVIS', 'Pelvis'), ('HAND', 'Hand / Wrist'), ('FOOT', 'Foot / Ankle'), ('SKULL', 'Skull'), ('ABDOMEN', 'Abdomen'), ('OTHER', 'Other')], default='CHEST', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('REPORTED', 'Reported')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('report', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_requests', to='doctors.doctorprofile')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
