# Generated by Django 5.1.1 on 2026-04-29 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_opdvisit_xrayrequest'),
        ('doctors', '0003_alter_specialty_options_doctorprofile_department_and_more'),
        ('pharmacy', '0002_alter_stockmovement_options_drug_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-issued_at']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='booked_by',
            field=models.ForeignKey(blank=True, help_text='If different from patient (e.g., admin/receptionist)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='follow_up_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='linked_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opd_visits', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='opd_ref',
            field=models.CharField(db_index=True, default='OPD-LEGACY', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='oxygen_saturation',
            field=models.CharField(blank=True, max_length=10, verbose_name='SpO₂ (%)'),
        ),
        migrations.AddField(
            model_name='opdvisit',
            name='pulse_rate',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pulse (bpm)'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, help_text='Linked inventory drug (set on dispensing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='pharmacy.drug'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='clinical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='linked_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_requests', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xray_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='urgency',
            field=models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT/Emergency')], default='ROUTINE', max_length=10),
        ),
        migrations.AddField(
            model_name='xrayrequest',
            name='xray_ref',
            field=models.CharField(db_index=True, default='XRY-LEGACY', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=16),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tele_room_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='bp',
            field=models.CharField(blank=True, max_length=20, verbose_name='Blood Pressure (mmHg)'),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('SEEN', 'Seen'), ('REFERRED', 'Referred'), ('DISCHARGED', 'Discharged')], db_index=True, default='WAITING', max_length=16),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='temperature',
            field=models.CharField(blank=True, max_length=10, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='opdvisit',
            name='visit_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(help_text='e.g. Twice daily, Every 8 hours', max_length=100),
        ),
        migrations.AlterField(
            model_name='xrayrequest',
            name='report',
            field=models.TextField(blank=True, verbose_name='Radiologist Report'),
        ),
        migrations.AlterField(
            model_name='xrayrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('REPORTED', 'Reported'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_fb412a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'status'], name='appointment_patient_44acdc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4d4b79_idx'),
        ),
        migrations.AddIndex(
            model_name='opdvisit',
            index=models.Index(fields=['visit_date', 'status'], name='appointment_visit_d_ca6e99_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayrequest',
            index=models.Index(fields=['status'], name='appointment_status_4677c9_idx'),
        ),
        migrations.AddIndex(
            model_name='xrayrequest',
            index=models.Index(fields=['urgency', 'status'], name='appointment_urgency_1e20a9_idx'),
        ),
    ]
