# Generated by Django 5.1.1 on 2026-04-29 10:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_prescription_options_appointment_booked_by_and_more'),
        ('billing', '0001_initial'),
        ('pharmacy', '0002_alter_stockmovement_options_drug_batch_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='Linked appointment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Staff-only notes (not shown to patient)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='pharmacy.drug'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('AED', 'UAE Dirham'), ('SAR', 'Saudi Riyal'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='AED', max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card / POS'), ('STRIPE', 'Stripe Online'), ('PAYPAL', 'PayPal'), ('INSURANCE', 'Insurance'), ('BANK', 'Bank Transfer'), ('WAIVED', 'Waived')], max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Stripe PI, bank ref, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='VAT %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MEDICINE', 'Medicine'), ('LAB_TEST', 'Lab Test'), ('XRAY', 'X-Ray / Radiology'), ('PROCEDURE', 'Procedure'), ('ROOM_CHARGE', 'Room Charge'), ('OTHER', 'Other')], default='CONSULTATION', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', 'status'], name='billing_inv_patient_ac2240_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['stripe_payment_intent_id'], name='billing_inv_stripe__b6d2d4_idx'),
        ),
    ]
